#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Data::Dumper;
use Encode qw/encode_utf8/;
use Number::Phone::JP::AreaCode::Parser;

$Data::Dumper::Terse  = 1;
$Data::Dumper::Indent = 1;

my $is_generate = $ARGV[0];

my $tsv_file = "$FindBin::Bin/../misc/area-code-jp.tsv";
my $hashref = Number::Phone::JP::AreaCode::Parser::parse_tsv_file($tsv_file);

my $areacode_map = {};
for my $pref (sort keys %$hashref) {
    for my $town (sort keys %{$hashref->{$pref}}) {
        my $area_code = $hashref->{$pref}->{$town}->{area_code};
        unless (ref $areacode_map->{$area_code}) {
            $areacode_map->{$area_code} = [];
        }
        push @{$areacode_map->{$area_code}}, encode_utf8($pref . $town);
    }
}

$Data::Dumper::Sortkeys = sub {
    my ($hash) = @_;
    return [sort keys %$hash];
};

my $areacode_map_str = Dumper($areacode_map);

if ($is_generate) {
    $areacode_map_str =~ s/(.*?\n)/      $1/g;
    chomp $areacode_map_str;

    my $output_file = "$FindBin::Bin/../lib/Number/Phone/JP/AreaCode/Data/AreaCode2Address.pm";
    open my $fh, '>', $output_file;
    print $fh <<"...";
package Number::Phone::JP::AreaCode::Data::AreaCode2Address;

### AUTO GENERATED BY `generate_areacode2address.pl`
### *** DO NOT EDIT THIS FILE WITH MANUAL LABOR ***

use strict;
use warnings;
use utf8;

use parent qw/Exporter/;

our \@EXPORT = qw/get_areacode2address_map/;

sub get_areacode2address_map {
    return $areacode_map_str;
}

1;

...
}
else {
    print $areacode_map_str;
}
