#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";

use Data::Dumper::AutoEncode;
use Encode qw/encode_utf8/;
use Number::Phone::JP::AreaCode::Parser;

$Data::Dumper::Terse  = 1;
$Data::Dumper::Indent = 1;

my $is_generate = $ARGV[0];

my $tsv_file    = "$FindBin::Bin/../misc/area-code-jp.tsv";
my $hashref_str = eDumper(Number::Phone::JP::AreaCode::Parser::parse_tsv_file($tsv_file));

if ($is_generate) {
    $hashref_str =~ s/(.*?\n)/      $1/g;
    chomp $hashref_str;

    open my $fh, '>', "$FindBin::Bin/../lib/Number/Phone/JP/AreaCode/Data/Address2AreaCode.pm";
    print $fh <<"...";
package Number::Phone::JP::AreaCode::Data::Address2AreaCode;

### AUTO GENERATED BY `generate_address2areacode.pl`

use strict;
use warnings;
use utf8;
use parent qw/Exporter/;

our \@EXPORT = qw/get_address2areacode_map/;

sub get_address2areacode_map {
    return $hashref_str;
}

1;

...
}
else {
    print $hashref_str;
}
