#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";

use Data::Dumper::AutoEncode;
use Encode qw/encode_utf8/;
use Number::Phone::JP::AreaCode::MasterData::TSV2Hash;

$Data::Dumper::Terse  = 1;
$Data::Dumper::Indent = 1;
$Data::Dumper::Deepcopy = 1;

my $is_generate = $ARGV[0];

my $tsv_file    = "$FindBin::Bin/../misc/area-code-jp.tsv";

$Data::Dumper::Sortkeys = sub {
    my ($hash) = @_;
    return [sort keys %$hash];
};

my $hashref_str = eDumper(Number::Phone::JP::AreaCode::MasterData::TSV2Hash::parse_tsv_file($tsv_file));

if ($is_generate) {
    chomp $hashref_str;

    open my $fh, '>', "$FindBin::Bin/../../lib/Number/Phone/JP/AreaCode/Data/Address2AreaCode.pm";
    print $fh <<"...";
package Number::Phone::JP::AreaCode::Data::Address2AreaCode;

### AUTO GENERATED BY `generate_address2areacode.pl`
### *** DO NOT EDIT THIS FILE WITH MANUAL LABOR ***

use strict;
use warnings;
use utf8;
use parent qw/Exporter/;

our \@EXPORT = qw/get_address2areacode_map/;

use constant ADDRESS_TO_AREACODE_MAP =>
$hashref_str;

sub get_address2areacode_map {
    return ADDRESS_TO_AREACODE_MAP;
}

1;

...
}
else {
    print $hashref_str;
}
